apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "minecraft-overseer.fullname" . }}
  labels:
    {{- include "minecraft-overseer.labels" . | nindent 4 }}
data:
  manifest.json: |-
{{.Values.manifest |toJson |indent 4}}
