apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft-overseer.fullname" . }}
  labels:
    {{- include "minecraft-overseer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mc
      protocol: TCP
      name: mc
  selector:
    {{- include "minecraft-overseer.selectorLabels" . | nindent 4 }}
